---
version: provider-v1alpha1 
name: gitlab
description: GitLab Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: username
  - name: password
parameters: 
  - name: region
    description: region to operate in
triggers: 
actions:
