---
version: provider-v1alpha1 
name: gitlab
description: GitLab Provider Definition
connection: 
  type: oauth
triggers: 
  - name: push
    description: push event into a project
    parameters:
    - name: project
      description: name of git project
      required: true
  - name: issues
    description: issue change event in a project
    parameters:
    - name: project
      description: name of git project
      required: true
actions:
