---
version: provider-v1alpha1 
name: aws
description: AWS Provider Definition
connection: 
  type: disabled
  connectionInfo:
  - name: access ID
  - name: secret key
parameters: 
  - name: region
    description: region to operate in
triggers: 
actions:
