---
version: provider-v1alpha1 
name: azure
description: Azure Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: access ID
  - name: secret key
parameters: 
  - name: region
    description: region to operate in
triggers: 
actions:
