---
version: provider-v1alpha1 
name: github
description: GitHub Provider Definition
connection: 
  type: oauth
triggers: 
  - name: push
    description: push event into a repository
    parameters:
    - name: repo
      description: name of git repository
      required: true
    - name: branch
      description: name of branch
      required: false
  - name: issues
    description: issue change event in a repository
    parameters:
    - name: repo
      description: name of git repository
      required: true
    - name: action
      description: issue action (opened, closed, assigned, etc)
      required: true
actions:
  - name: issue
    description: open an issue 
    parameters:
    - name: action
      description: issue action (open, close, assign, etc)
      required: true
    - name: name
      description: name of the issue
      required: false
