---
version: provider-v1alpha1 
name: slack
description: Slack Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: username
  - name: password
parameters: 
triggers: 
actions:
