---
version: provider-v1alpha1 
name: twilio
description: Twilio Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: token
    description: personal access token
triggers: 
actions:
  - name: send
    description: send a message to a phone number 
    parameters:
    - name: phone
      description: channel to send to
      required: true
    - name: message
      description: message to send
      required: true
