---
version: provider-v1alpha1 
name: twilio
description: Twilio Provider Definition
connection: 
  type: simple
  infoUrl: https://www.twilio.com/console
  infoText: Click here to view Twilio Account SID and Auth Token
  entity: twilio:accounts
  connectionInfo:
  - name: account
    description: account name
    type: name
  - name: sid
    description: account SID
    type: password
  - name: token
    description: auth token
    type: password
triggers: 
actions:
  - name: send
    description: send a message to a phone number 
    parameters:
    - name: account
      description: account name
      entity: twilio:accounts
      required: true 
    - name: to
      description: phone number to send SMS to
      required: true
    - name: message
      description: message to send
      required: true
    - name: from
      description: phone number to send SMS from
      required: true
    - name: mediaUrl
      description: URL of image to send with SMS
      required: false
