---
version: provider-v1alpha1 
name: circleci
description: CircleCI Provider Definition
connection: 
  type: disabled
  connectionInfo:
  - name: userid
  - name: access token
parameters: 
  - name: region
    description: region to operate in
triggers: 
actions:
