---
version: snap-v1alpha1 
name: docker-slack
description: Docker push -> Slack notification
trigger: docker-push
actions:
  - slack-message
parameters: 
  - name: repo
    description: name of docker repository
  - name: channel
    description: name of slack channel
config:
  - name: docker-push
    provider: docker
    account: docker:accounts:default
    event: push
    repo: $repo
  - name: slack-message
    provider: slack
    workspace: slack:workspaces:default
    action: send
    channel: $channel
    message: new image pushed into $repo in dockerhub
