---
version: snap-v1alpha1 
name: github-gcpbuild-slack
description: GitHub merge -> Google Cloud build / Slack message
trigger: github-push
actions:
  - gcp-build
  - slack-message
parameters: 
  - name: repo
    description: name of git repository
  - name: branch
    description: name of branch
  - name: channel
    description: name of slack channel
config: 
  - name: github-push
    provider: github
    event: push
    repo: $repo
    branch: master
  - name: gcp-build
    provider: gcp
    action: build
    repo: https://github.com/$repo
  - name: slack-message
    provider: slack
    action: send
    channel: $channel
    message: kicked off new build of $repo:$branch
