---
version: snap-v1alpha1 
name: github-gcpbuild-slack
description: GitHub merge -> Google Cloud Build, Slack message
trigger: github-push
actions:
  - gcp-build
  - slack-message
parameters: 
  - name: repo
    description: name of git repository
  - name: project
    description: project ID
  - name: image
    description: image name
  - name: channel
    description: slack channel
config: 
  - name: github-push
    provider: github
    event: push
    repo: $repo
  - name: gcp-build
    provider: gcp
    action: build
    project: $project
    image: $image
    repo: $.repository.html_url
  - name: slack-message
    provider: slack
    action: send
    channel: $channel
    message: built $repo into gcr.io/$project/$image
