---
version: snap-v1alpha1 
name: github-gcpbuild-slack
description: GitHub merge -> Google Cloud build / Slack
trigger: github
actions:
  - gcp
  - slack
parameters: 
  - name: repo
    description: name of git repository
  - name: branch
    description: name of branch
  - name: channel
    description: name of slack channel
config: 
  - github:
    event: push
    repo: $repo
    branch: master
  - slack:
    action: send
    channel: $channel
    message: received push on $repo:$branch
  - gcp:
    action: gcpbuild
    repo: https://github.com/$repo
  - slack:
    action: send
    channel: $channel
    message: kicked off new build of $repo:$branch
