---
version: snap-v1alpha1 
name: github-issue-pagerduty
description: GitHub issue -> PagerDuty incident
trigger: github-issue
actions:
  - pagerduty-incident
parameters: 
  - name: repo
    description: github repository
  - name: service
    description: pagerduty service
    entity: pagerduty:services
config:
  - name: github-issue
    provider: github
    event: issues
    repo: $repo
  - name: pagerduty-incident
    provider: pagerduty
    service: $service
    action: create
    title: $.issue.title
    details: received event "$.action" on issue "$.issue.title" in repo $repo

