---
version: snap-v1alpha1 
name: github-gcpbuild-slack
description: GitHub merge -> Google Cloud build / Slack
tools:
  trigger:
    github
  actions:
    - gcpbuild
    - slack
parameters: 
  - name: repo
    description: name of git repository
  - name: branch
    description: name of branch
  - name: channel
    description: name of slack channel
trigger: 
  name: github/merge
  parameters:
    repo: $repo
    branch: $branch
actions:
  - name: gcpbuild/build
    description: Build project using google cloud build
    parameters: 
      repo: $repo
      branch: $branch
  - name: slack/send
    action: Send a message to a slack channel
    parameters: 
      channel: $channel
      message: kicked off new build of $repo:$branch
