---
version: snap-v1alpha1 
name: github-issue-slack
description: GitHub new issue -> Slack notification
trigger: github-issue
actions:
  - slack-message
parameters: 
  - name: repo
    description: name of git repository
  - name: channel
    description: name of slack channel
config:
  - name: github-issue
    provider: github
    repo: $repo
    event: issues
  - name: slack-message
    provider: slack
    workspace: slack:workspaces:default
    action: send
    channel: $channel
    message: received event $.action on issue $.issue.title in repo $repo
