---
version: snap-v1alpha1 
name: github-slack
description: GitHub push master -> Slack notification
trigger: github-push
actions:
  - slack-message
parameters: 
  - name: repo
    description: name of git repository
  - name: channel
    description: name of slack channel
config:
  - name: github-push
    provider: github
    repo: $repo
    event: push
  - name: slack-message
    provider: slack
    workspace: slack:workspaces:default
    action: send
    channel: $channel
    message: received push on $repo
