---
version: snap-v1alpha1 
name: github-issue-sendgrid
description: GitHub issue -> Sendgrid email notification
trigger: github-issue
actions:
  - sendgrid-message
parameters: 
  - name: repo
    description: name of git repository
  - name: from
    description: email to send from
  - name: to
    description: email to send to
config:
  - name: github-issue
    provider: github
    repo: $repo
    event: issues
  - name: sendgrid-message
    provider: sendgrid
    account: sendgrid:accounts:default
    action: send
    from: $from
    to: $to
    subject: repo $repo just received an issue
    message: received event $.action on issue $.issue.title in repo $repo

