---
version: snap-v1alpha1 
name: gitlab-issues-slack
description: GitLab issues event -> Slack notification for John
trigger: gitlab-issue
actions:
  - slack-message
parameters: 
  - name: project
    description: name of git project
  - name: channel
    description: name of slack channel
config:
  - name: gitlab-issue
    provider: gitlab
    project: $project
    event: issues
  - name: slack-message
    provider: slack
    workspace: slack:workspaces:default
    action: send
    channel: $channel
    message: received event "$.object_attributes.action" on issue "$.object_attributes.title" in project "$project"

