---
version: provider-v1alpha1 
name: docker
description: Docker Provider Definition
connection: 
  type: simple
  entity: docker:accounts
  connectionInfo:
  - name: username
    description: user name
    type: name
  - name: password
    description: triggers require password (not a personal access token)
    type: password
triggers: 
  - name: push
    description: push event into a repository
    parameters:
    - name: account
      description: account name
      entity: docker:accounts
      required: true 
    - name: repo
      description: name of docker repository
      required: true 
actions:
