---
version: provider-v1alpha1 
name: docker
description: Docker Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: token
    description: personal access token
triggers: 
actions:
