---
version: provider-v1alpha1 
name: docker
description: Docker Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: username
    description: user name
  - name: password
    description: triggers require password (not a personal access token)
    password: true
triggers: 
  - name: push
    description: push event into a repository
    parameters:
    - name: repo
      description: name of docker repository
      required: true 
actions:
