---
version: provider-v1alpha1 
name: slack
description: Slack Provider Definition
connection: 
  type: simple
  infoUrl: https://api.slack.com/legacy/custom-integrations/legacy-tokens
  infoText: Click here to create a legacy access token
  connectionInfo:
  - name: token
    description: personal access token
triggers: 
actions:
  - name: send
    description: send a message to a channel 
    parameters:
    - name: channel
      description: channel to send to
      required: true
    - name: message
      description: message to send
      required: true
