---
version: provider-v1alpha1 
name: pagerduty
description: Pagerduty Provider Definition
connection: 
  type: simple
  connectionInfo:
  - name: token
    description: personal access token
triggers: 
actions:
