---
version: provider-v1alpha1 
name: pagerduty
description: Pagerduty Provider Definition
connection: 
  type: oauth
  entity: pagerduty:services
  connectionInfo:
  - name: service
    description: service name
triggers: 
  - name: incident.trigger
    description: new incident triggered
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
  - name: incident.acknowledge
    description: incident acknowledged
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
  - name: incident.resolve
    description: incident resolved
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
  - name: incident.assign
    description: incident assigned
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
  - name: incident.escalate
    description: incident escalated
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
  - name: incident.delegate
    description: incident delegated
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
actions:
  - name: create
    description: create incident
    parameters:
    - name: service
      description: name of pagerduty service
      entity: pagerduty:services
      required: true
    - name: title
      description: title of incident
      required: true
    - name: details
      description: incident details
      required: false
    - name: urgency
      description: urgency of incident
      required: false
      
